In [1]:
from bs4 import BeautifulSoup
import requests as rt
import pandas as pd

In [23]:
url = 'https://josaa.admissions.nic.in/seatinfo/root/seatmatrixinfo.aspx'
params = {
    #"ctl00$ContentPlaceHolder1$ddlroundno": 
    "ctl00$ContentPlaceHolder1$ddlInstype": "0",
    "ctl00$ContentPlaceHolder1$ddlInstitute": "0",
    "ctl00$ContentPlaceHolder1$ddlBranch": "0",
    "ctl00$ContentPlaceHolder1$btnSubmit": "Submit"
}

In [30]:
def scrape(Year):   
    with rt.Session() as s:
        R = s.get(url)
        data = {}

        #data.update({tag['name']: tag['value'] for tag in BeautifulSoup(R.content, 'lxml').select('input[name^=__]')})
        #data["ctl00$ContentPlaceHolder1$ddlYear"] = Year
        #R = s.post(url, data=data)

        #data.update({tag['name']: tag['value'] for tag in BeautifulSoup(R.content, 'lxml').select('input[name^=__]')})
        #data["ctl00$ContentPlaceHolder1$ddlroundno"] = Round
        #R = s.post(url, data=data)

        for key, value in params.items():
            data.update({tag['name']: tag['value'] for tag in BeautifulSoup(R.content, 'lxml').select('input[name^=__]')})
            data[key] = value
            R = s.post(url, data=data)
        #print(R.text)
        #print(data)

    table = BeautifulSoup(R.text, 'lxml').find(id = 'GridView1')
    #print(table)
    df = pd.read_html(table.prettify())[0]
    df.dropna(inplace = True, how="all")
    
    df['Year'] = Year
    #df['Round'] = Round
    #df['Opening Rank'] = df['Opening Rank'].astype(int)
    #df['Closing Rank'] = df['Closing Rank'].astype(int)
    
    return df

In [31]:
df = scrape('2021')
df

,Institute Name,Program Name,State/All India Seats,Seat Pool,OPEN,OPEN-PwD,GEN-EWS,GEN-EWS-PwD,SC,SC-PwD,ST,ST-PwD,OBC-NCL,OBC-NCL-PwD,Total(includes Female Supernumerary),Program-Total Seat Capacity Female Supernumerary,Year
0,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",All India,Gender-Neutral,21,0,5,0,9,1,3,0,13,1,53,62 4,2021
1,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",All India,Female-only (including Supernumerary),5,0,1,0,1,1,1,0,4,0,"13 (including ""4"" Supernumerary)",62 4,2021
2,Indian Institute of Technology Bhubaneswar,"Computer Science and Engineering (4 Years, Bac...",All India,Gender-Neutral,22,1,4,0,7,1,4,1,13,1,54,63 5,2021
3,Indian Institute of Technology Bhubaneswar,"Computer Science and Engineering (4 Years, Bac...",All India,Female-only (including Supernumerary),5,0,1,0,1,1,1,0,4,1,"14 (including ""5"" Supernumerary)",63 5,2021
4,Indian Institute of Technology Bhubaneswar,"Electrical Engineering (4 Years, Bachelor of T...",All India,Gender-Neutral,22,1,6,0,8,0,4,0,14,1,56,62 8,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2102,"North-Eastern Hill University, Shillong","Biomedical Engineering (4 Years, Bachelor of T...",All India,Gender-Neutral,7,1,2,0,3,0,2,0,5,0,20,20 0,2021
2103,"North-Eastern Hill University, Shillong","Biomedical Engineering (4 Years, Bachelor of T...",All India,Female-only (including Supernumerary),0,0,0,0,0,0,0,0,0,0,"0 (including ""0"" Supernumerary)",20 0,2021
2104,"North-Eastern Hill University, Shillong","Energy Engineering (4 Years, Bachelor of Techn...",All India,Gender-Neutral,7,1,2,0,3,0,2,0,5,0,20,20 0,2021
2105,"North-Eastern Hill University, Shillong","Energy Engineering (4 Years, Bachelor of Techn...",All India,Female-only (including Supernumerary),0,0,0,0,0,0,0,0,0,0,"0 (including ""0"" Supernumerary)",20 0,2021
2106,NaN,NaN,NaN,Total Seats,20755,1074,4997,261,7330,401,4127,201,12648,659,52453,50016 2437,2021

In [33]:
df.columns

Index(['Institute Name', 'Program Name', 'State/All India Seats', 'Seat Pool',
       'OPEN', 'OPEN-PwD', 'GEN-EWS', 'GEN-EWS-PwD', 'SC', 'SC-PwD', 'ST',
       'ST-PwD', 'OBC-NCL', 'OBC-NCL-PwD',
       'Total(includes Female Supernumerary)',
       'Program-Total  Seat Capacity  Female Supernumerary', 'Year'],
      dtype='object')